[package]
name = "discord-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"