# Railway project configuration for a Rust app

[build]
builder = "nixpacks"

[env]
PORT = "8080"

[deploy]
command = "cargo run --release"
healthcheckPath = "/send"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"